### ISSUE TITLE
Geopackage cleanup = NotImplementedError

### ISSUE THREAD

**Issue by marcusmohr** [mapproxy/mapproxy#379] opened 2018-09-07 16:05 UTC
When I use geopackage and the "levels" option is set to "true" a cleanup process throws the following error: 

Traceback (most recent call last):
  File "/usr/bin/mapproxy-seed", line 9, in <module>
    load_entry_point('MapProxy==1.11.0', 'console_scripts', 'mapproxy-seed')()
  File "/usr/lib/python2.7/dist-packages/mapproxy/seed/script.py", line 361, in main
    return SeedScript()()
  File "/usr/lib/python2.7/dist-packages/mapproxy/seed/script.py", line 255, in __call__
    skip_geoms_for_last_levels=options.geom_levels)
  File "/usr/lib/python2.7/dist-packages/mapproxy/seed/cleanup.py", line 58, in cleanup
    seed_progress=seed_progress,
  File "/usr/lib/python2.7/dist-packages/mapproxy/seed/cleanup.py", line 122, in tilewalker_cleanup
    tile_walker.walk()
  File "/usr/lib/python2.7/dist-packages/mapproxy/seed/seeder.py", line 322, in walk
    self._walk(bbox, self.task.levels)
  File "/usr/lib/python2.7/dist-packages/mapproxy/seed/seeder.py", line 371, in _walk
    all_subtiles=all_subtiles)
  File "/usr/lib/python2.7/dist-packages/mapproxy/seed/seeder.py", line 371, in _walk
    all_subtiles=all_subtiles)
  File "/usr/lib/python2.7/dist-packages/mapproxy/seed/seeder.py", line 371, in _walk
    all_subtiles=all_subtiles)
  File "/usr/lib/python2.7/dist-packages/mapproxy/seed/seeder.py", line 371, in _walk
    all_subtiles=all_subtiles)
  File "/usr/lib/python2.7/dist-packages/mapproxy/seed/seeder.py", line 396, in _walk
    self.tile_mgr.is_stale(t)]
  File "/usr/lib/python2.7/dist-packages/mapproxy/cache/tile.py", line 178, in is_stale
    if not self.is_cached(tile):
  File "/usr/lib/python2.7/dist-packages/mapproxy/cache/tile.py", line 164, in is_cached
    self.cache.load_tile_metadata(tile)
  File "/usr/lib/python2.7/dist-packages/mapproxy/cache/base.py", line 83, in load_tile_metadata
    raise NotImplementedError()
NotImplementedError

I am using Mapproxy 1.11 and Debian Jessie

**Comment by justb4** [comment] 2023-07-27 14:44
I think I found the possible cause:

[geopackage.py](https://github.com/mapproxy/mapproxy/blob/master/mapproxy/cache/geopackage.py)
contains the `GeopackageCache` and `GeopackageLevelCache` (per Level). The latter holds a reference to an `GeopackageCache` instance delegating most `TileCacheBase` methods to `GeopackageCache`. For example:
on [geopackage.py line 483](https://github.com/mapproxy/mapproxy/blob/master/mapproxy/cache/geopackage.py#L483)

```
    def store_tile(self, tile, dimensions=None):
        if tile.stored:
            return True

        return self._get_level(tile.coord[2]).store_tile(tile, dimensions=dimensions)
```

Through the z-coord, `zoom` level `tile.coord[2]` it can get to the `GeopackageCache` instance and call `store_tile()` there.

For the method `load_tile_metadata()` this delegation seems to be missing, hence the  `NotImplementedError `. 

IMHO this could be implemented similarly in `GeopackageLevelCache` like:

```
    def load_tile_metadata(self, tile, dimensions=None):
        return self._get_level(tile.coord[2]).load_tile_metadata(tile, dimensions=dimensions)
```

From reading the code, could be wrong..Will try out.

**Comment by justb4** [comment] 2023-07-27 16:02
Confirmed, tested locally, indeed can do clean task now where `levels: false`. Will PR.

**Comment by weskamm** [comment] 2023-08-02 14:57
closed by https://github.com/mapproxy/mapproxy/pull/697

**Closed by weskamm** 2023-08-02 14:57 UTC
