### ISSUE TITLE
`escape` no longer included in cgi module

### ISSUE THREAD

**Issue by stuart23** [mapproxy/mapproxy#467] opened 2020-07-13 18:16 UTC
The `escape` function is no longer in the cgi module as of Python 3.8.

To get around this, I am currently building containers with this:
`RUN echo "from html import escape" >> `python -c "import cgi; print(cgi.__file__)"``

Obviously this is not ideal, and the escape function should be imported from `html` instead. Only difference here is that the `quote` kwarg defaults to True in html, and False in cgi.

https://docs.python.org/3.7/library/cgi.html#cgi.escape
https://docs.python.org/3.8/library/html.html#html.escape

**Comment by martijn-heil** [comment] 2020-07-15 11:18
Duplicate of #462

**Closed** 2020-07-15 12:33 UTC
