### ISSUE TITLE
Add support for ArcGIS ImageServer "source"

### ISSUE THREAD

**Issue by SantiagoHorcajo** [mapproxy/mapproxy#253] opened 2016-09-19 11:55 UTC
Thank you very much for recently added support for ArcGIS MapServer "source". I think it's very easy to add basic support for ImageServer services. There are some differences between MapServer and ImageServer services. Typical (and existing) URL for MapServer services is:
      http://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer
and for ImageServer services:
      http://landsat2.arcgis.com/arcgis/rest/services/Landsat8_Views/ImageServer
The first diference is the last part of the URL, ImageServer vs MapServer. And the second one is how to recover images from the server. For MapServer services is:
      http://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/export?(parameters)
For basic ImageServer support the same parameters can be used, using exportImage instead of export:
      http://landsat2.arcgis.com/arcgis/rest/services/Landsat8_Views/ImageServer/exportImage?(parameters)

Thanks in advance,
Santiago Horcajo

**Comment by olt** [comment] 2016-09-19 12:20
I think this is a duplicate of #235

**Closed by olt** 2016-09-19 12:20 UTC

**Comment by SantiagoHorcajo** [comment] 2016-09-20 08:22
Yeah, you're right. Thank you very much for addressing this issue.
